#!/usr/bin/env bash
# vim: ft=sh

declare -A _CHM_TEST_POSITION # "NL" or "EOL"
declare -A _CHM_DATABASE
declare -A _CHM_PARSED

TEST_MARKER=${TEST_MARKER:-':'}
META_MARKER=${META_MARKER:-'@'}

for opt in "$@"
do
  case "$opt" in
    '-q' )
      QUIET=true
      shift 1
      ;;
  esac
done

_tput() { $_CHM_TPUT "$@"; }

eecho() { echo "$@" >&2; }

error() {
  eecho -n "$(_tput bold)$(_tput setaf 1)===> Parse error:$(_tput sgr0) "
  eecho "${1} (L${LINE_NUMBER})"

  local begin_col=$((LINE_NUMBER - 3))
  local end_col=$((LINE_NUMBER + 3))
  local file_max_lines=$(wc -l < "${TARGET_FULLPATH}")

  [ ${begin_col} -lt 1 ] && begin_col=1
  [ ${end_col} -gt "${file_max_lines}" ] && end_col=${file_max_lines}

  local cols_count=${begin_col}
  local padding=${#end_col}

  while read -r line; do
    if [ ${cols_count} -eq "${LINE_NUMBER}" ]; then
      eecho -n '->'
      eecho " $(printf "%${padding}d" ${cols_count}) |  $(_tput setaf 1)${line}$(_tput sgr0)"
    else
      eecho -n '  '
      eecho " $(printf "%${padding}d" ${cols_count}) |  ${line}"
    fi
    ((cols_count++))
  done < <(sed -n "${begin_col},${end_col}p" "${TARGET_FULLPATH}")
  eecho

  PARSE_ERROR=true
  _CHM_DATABASE[${TARGET_FULLPATH},parse_error]=true
}

valid() {
  local left=${_CHM_DATABASE[${TARGET_FULLPATH},${LINE_NUMBER},${TEST_INDEX},left]}
  local mid=${_CHM_DATABASE[${TARGET_FULLPATH},${LINE_NUMBER},${TEST_INDEX},mid]}
  local right=${_CHM_DATABASE[${TARGET_FULLPATH},${LINE_NUMBER},${TEST_INDEX},right]}

  case ${mid} in
    '='|'!='|'=~'|'!=~' )
      :
      ;;
    ':'|'!:'|':~'|'!:~'|'::' )
      case ${left} in
        'status' )
          case ${mid} in
            ':~'|'!:~'|'::' )
              error "\"${mid}\": invalid matcher"
              ;;
          esac
          [ "${right}" -ge 0 ] > /dev/null 2>&1 || error "\"${right}\": invalid status code"
          ;;
        'output'|'stdout'|'stderr' )
          case ${mid} in
            '::' )
              case ${right} in
                'None' )
                  :
                  ;;
                * )
                  error "\"${right}\": invalid keyword"
                  ;;
              esac
              ;;
          esac
          ;;
        * )
          error "\"${left}\": invalid resource"
          ;;
      esac
      ;;
    * )
      error "\"${mid}\": invalid matcher"
      ;;
  esac
}

parse_test_dq_bs() {
  case ${1} in
    * )
      TEST_COMMENT="${TEST_COMMENT}""${1}"
      PARSE_METHOD="parse_test_dq"
      ;;
  esac
}

parse_test_dq() {
  case ${1} in
    '"' )
      TEST_COMMENT="${TEST_COMMENT}""\""
      PARSE_METHOD="${PARENT_PARSE_METHOD}"
      ;;
    "\\" )
      TEST_COMMENT="${TEST_COMMENT}""\\"
      PARSE_METHOD="parse_test_dq_bs"
      ;;
    "" )
      error "\"${TEST_COMMENT}\": quote is not closed"
      PARSE_METHOD="parse_nl"
      TEST_COMMENT=""
      PARENT_PARSE_METHOD=""
      ;;
    * )
      TEST_COMMENT="${TEST_COMMENT}""${1}"
      ;;
  esac
}

parse_test_sq() {
  case ${1} in
    "'" )
      TEST_COMMENT="${TEST_COMMENT}""'"
      PARSE_METHOD="${PARENT_PARSE_METHOD}"
      ;;
    "" )
      error "\"${TEST_COMMENT}\": quote is not closed"
      PARSE_METHOD="parse_nl"
      TEST_COMMENT=""
      PARENT_PARSE_METHOD=""
      ;;
    * )
      TEST_COMMENT="${TEST_COMMENT}""${1}"
      ;;
  esac
}

parse_test_bs() {
  case ${1} in
    * )
      TEST_COMMENT="${TEST_COMMENT}""${1}"
      PARSE_METHOD="${PARENT_PARSE_METHOD}"
      ;;
  esac
}

parse_test_right() {
  PARENT_PARSE_METHOD="${FUNCNAME}"
  case ${1} in
    '"' )
      TEST_COMMENT="${TEST_COMMENT}""\""
      PARSE_METHOD="parse_test_dq"
      ;;
    "'" )
      TEST_COMMENT="${TEST_COMMENT}""'"
      PARSE_METHOD="parse_test_sq"
      ;;
    "\\" )
      TEST_COMMENT="${TEST_COMMENT}""\\"
      PARSE_METHOD="parse_test_bs"
      ;;
    " "|"\t" )
      _CHM_DATABASE[${TARGET_FULLPATH},${LINE_NUMBER},${TEST_INDEX},right]="${TEST_COMMENT}"
      valid
      PARSE_METHOD="parse_test_main"
      TEST_COMMENT=""
      PARENT_PARSE_METHOD=""
      ;;
    "" )
      _CHM_TEST_POSITION[${TARGET_FULLPATH},${LINE_NUMBER}]="${COMMENT_IN}"
      _CHM_DATABASE[${TARGET_FULLPATH},${LINE_NUMBER},${TEST_INDEX},right]="${TEST_COMMENT}"
      _CHM_DATABASE[${TARGET_FULLPATH},${LINE_NUMBER},max_test_index]="${TEST_INDEX}"
      TEST_EXIST=true
      valid
      PARSE_METHOD="parse_nl"
      TEST_COMMENT=""
      PARENT_PARSE_METHOD=""
      ;;
    * )
      TEST_COMMENT="${TEST_COMMENT}""${1}"
      ;;
  esac
}

parse_test_mid() {
  case ${1} in
    '='|':'|'!'|'~' )
      TEST_COMMENT="${TEST_COMMENT}""${1}"
      ;;
    " "|"\t" )
      error "\"${TEST_COMMENT}\": empty value"
      PARSE_METHOD="parse_test_main"
      TEST_COMMENT=""
      PARENT_PARSE_METHOD=""
      ;;
    "" )
      error "\"${TEST_COMMENT}\": empty value"
      PARSE_METHOD="parse_nl"
      TEST_COMMENT=""
      PARENT_PARSE_METHOD=""
      ;;
    * )
      _CHM_DATABASE[${TARGET_FULLPATH},${LINE_NUMBER},${TEST_INDEX},mid]="${TEST_COMMENT}"
      TEST_COMMENT=""
      PARSE_METHOD="parse_test_right"
      parse_test_right "${1}"
      ;;
  esac
}

parse_test_left() {
  PARENT_PARSE_METHOD="${FUNCNAME}"
  case ${1} in
    '"' )
      TEST_COMMENT="${TEST_COMMENT}""\""
      PARSE_METHOD="parse_test_dq"
      ;;
    "'" )
      TEST_COMMENT="${TEST_COMMENT}""'"
      PARSE_METHOD="parse_test_sq"
      ;;
    "\\" )
      TEST_COMMENT="${TEST_COMMENT}""\\"
      PARSE_METHOD="parse_test_bs"
      ;;
    "!"|"="|":" )
      _CHM_DATABASE[${TARGET_FULLPATH},${LINE_NUMBER},${TEST_INDEX},left]="${TEST_COMMENT}"
      TEST_COMMENT=""
      PARSE_METHOD="parse_test_mid"
      parse_test_mid "${1}"
      ;;
    ' '|'\t' )
      error "\"${TEST_COMMENT}\": invalid token"
      PARSE_METHOD="parse_test_main"
      TEST_COMMENT=""
      PARENT_PARSE_METHOD=""
      ;;
    '' )
      error "\"${TEST_COMMENT}\": invalid token"
      PARSE_METHOD="parse_nl"
      TEST_COMMENT=""
      PARENT_PARSE_METHOD=""
      ;;
    * )
      TEST_COMMENT="${TEST_COMMENT}""${1}"
      ;;
  esac
}

parse_test_main() {
  case ${1} in
    " "|"\t" )
      :
      ;;
    "" )
      [ "${_CHM_DATABASE[${TARGET_FULLPATH},${LINE_NUMBER},0,left]}" ] && {
        _CHM_TEST_POSITION[${TARGET_FULLPATH},${LINE_NUMBER}]="${COMMENT_IN}"
        _CHM_DATABASE[${TARGET_FULLPATH},${LINE_NUMBER},max_test_index]="${TEST_INDEX}"
      }
      PARSE_METHOD="parse_nl"
      TEST_COMMENT=""
      ;;
    * )
      ((TEST_INDEX++))
      PARSE_METHOD="parse_test_left"
      parse_test_left "${1}"
      ;;
  esac
}

parse_meta_value() {
  case ${1} in
    '' )
      _CHM_DATABASE[${TARGET_FULLPATH},meta,${META_KEY}]="$(echo "${META_VAL}" | sed -e 's/^[ \t]*//' -e 's/[ \t]*$//')"
      PARSE_METHOD='parse_nl'
      META_KEY=''
      META_VAL=''
      ;;
    * )
      META_VAL="${META_VAL}${1}"
      ;;
  esac
}

parse_meta_key() {
  case ${1} in
    ':' )
      PARSE_METHOD="parse_meta_value"
      ;;
    '' )
      error "\"${META_KEY}\": invalid token"
      PARSE_METHOD='parse_nl'
      META_KEY=''
      ;;
    * )
      META_KEY="${META_KEY}${1}"
      ;;
  esac
}

parse_meta_main() {
  case ${1} in
    " "|"\t" )
      :
      ;;
    "" )
      PARSE_METHOD='parse_nl'
      ;;
    * )
      PARSE_METHOD='parse_meta_key'
      parse_meta_key "${1}"
      ;;
  esac
}

parse_marker() {
  case ${1} in
    "${TEST_MARKER}" )
      PARSE_METHOD="parse_test_main"
      ;;
    "${META_MARKER}" )
      PARSE_METHOD="parse_meta_main"
      ;;
    "" )
      PARSE_METHOD="parse_nl"
      ;;
    * )
      PARSE_METHOD="parse_main"
      ;;
  esac
}

parse_dq_bs() {
  case ${1} in
    "" )
      PARSE_METHOD="parse_dq"
      ;;
    * )
      PARSE_METHOD="parse_dq"
      ;;
  esac
}

parse_dq() {
  case ${1} in
    "\\" )
      PARSE_METHOD="parse_dq_bs"
      ;;
    '"' )
      PARSE_METHOD="parse_main"
      ;;
    "" )
      ;;
    * )
      :
      ;;
  esac
}

parse_sq() {
  case ${1} in
    "'" )
      PARSE_METHOD="parse_main"
      ;;
    "" )
      ;;
    * )
      :
      ;;
  esac
}

parse_bs() {
  case ${1} in
    "" )
      PARSE_METHOD="parse_main"
      ;;
    * )
      PARSE_METHOD="parse_main"
      ;;
  esac
}

parse_main() {
  case ${1} in
    "#" )
      PARSE_METHOD="parse_marker"
      COMMENT_IN="EOL"
      ;;
    "\\" )
      PARSE_METHOD="parse_bs"
      ;;
    "'" )
      PARSE_METHOD="parse_sq"
      ;;
    '"' )
      PARSE_METHOD="parse_dq"
      ;;
    "" )
      PARSE_METHOD="parse_nl"
      ;;
    * )
      ;;
  esac
}

parse_nl_space() {
  case ${1} in
    "#" )
      PARSE_METHOD="parse_marker"
      COMMENT_IN="NL"
      ;;
    " "|"\t" )
      PARSE_METHOD="parse_nl_space"
      ;;
    "\\" )
      PARSE_METHOD="parse_bs"
      ;;
    "'" )
      PARSE_METHOD="parse_sq"
      ;;
    '"' )
      PARSE_METHOD="parse_dq"
      ;;
    "" )
      PARSE_METHOD="parse_nl"
      ;;
    * )
      PARSE_METHOD="parse_main"
      ;;
  esac
}

parse_nl() {
  case ${1} in
    "#" )
      PARSE_METHOD="parse_marker"
      COMMENT_IN="NL"
      ;;
    " "|"\t" )
      PARSE_METHOD="parse_nl_space"
      ;;
    "\\" )
      PARSE_METHOD="parse_bs"
      ;;
    "'" )
      PARSE_METHOD="parse_sq"
      ;;
    '"' )
      PARSE_METHOD="parse_dq"
      ;;
    "" )
      PARSE_METHOD="parse_nl"
      ;;
    * )
      PARSE_METHOD="parse_main"
      ;;
  esac
}

parse() {
  TARGET_FULLPATH="${1}"
  local line
  local char

  while IFS= read -r line; do
    while IFS= read -r -n 1 char; do
      ${PARSE_METHOD} "${char}"
      ((OFFSET_NUMBER++))
    done < <(echo "${line}")
    OFFSET_NUMBER=1
    TEST_INDEX=-1 # reset index. '-1' means that there is no test.
    ((LINE_NUMBER++))
  done < "${TARGET_FULLPATH}"
}

main() {
  PARSE_ERROR=false    # Any even one of the multiple files
  TEST_NOT_FOUND=false # Any even one of the multiple files
  PARSE_DUP=false      # Any even one of the multiple files

  [ -f "${_CHM_PARSER_FILE}" ] && source "${_CHM_PARSER_FILE}"

  for i in "$@"
  do
    [ "$QUIET" ] || echo "==> Parsing: \"${i}\""
    if ! [ "${_CHM_PARSED[${i}]}" ]; then
      LINE_NUMBER=1
      OFFSET_NUMBER=1
      TEST_INDEX=-1
      PARSE_METHOD="parse_nl" # initial parse-method
      TEST_EXIST=false

      parse "${i}"
      _CHM_PARSED[${i}]='parsed'

      ${TEST_EXIST} || {
        [ "$QUIET" ] || eecho "===> test not found"
        [ "$QUIET" ] || eecho
        TEST_NOT_FOUND=true
        _CHM_DATABASE[${TARGET_FULLPATH},parse_error]=true
      }
    else
      [ "$QUIET" ] || eecho "===> already parsed"
      [ "$QUIET" ] || eecho
      PARSE_DUP=true
    fi
  done

  {
    declare -p _CHM_TEST_POSITION
    declare -p _CHM_DATABASE
    declare -p _CHM_PARSED
  } > "${_CHM_PARSER_FILE}"

  $_CHM_DEBUG && {
    echo " * $(declare -p _CHM_TEST_POSITION)"
    echo " * $(declare -p _CHM_DATABASE)"
    echo " * $(declare -p _CHM_PARSED)"
  }

  if ${PARSE_ERROR}; then
    return 10
  elif ${TEST_NOT_FOUND}; then
    return 11
  elif ${PARSE_DUP}; then
    return 12
  else
    return 0
  fi
}

main "$@"
