#!/usr/bin/env bash

_CHM_NAME='chocomint.sh'
_CHM_VERSION='0.3.0'

export _CHM_LIBEXEC="$(dirname -- "$(readlink -f -- "${BASH_SOURCE:-$0}")")"
source ${_CHM_LIBEXEC}/chocomint-lib/outputs

export _CHM_TEST_RESULTS_FILE="/tmp/_chm_test_results.$$"
# variables in _CHM_TEST_RESULTS_FILE
export _CHM_TEST_FAILURE=0
export _CHM_TEST_SUCCESS=0
export _CHM_TEST_COUNT=0
export _CHM_CMD_SUCCESS=0
export _CHM_CMD_COUNT=0
export _CHM_FAILURE=false


_chm_system_check() {
  #
  # "tput" exist check
  #
  if type tput > /dev/null 2>&1
  then
    export _CHM_TPUT="tput"
  else
    echo "WARN: \"tput\" command is not found"
    echo "WARN: run without coloring"
    echo
    export _CHM_TPUT="true"
  fi

  #
  # "bc" exist check
  #
  if type bc > /dev/null 2>&1
  then
    export _CHM_BC_COMMAND_EXIST=true
  else
    echo "WARN: \"bc\" command is not found"
    echo "WARN: unable to display the execution time of commands"
    echo
    export _CHM_BC_COMMAND_EXIST=false
  fi
}


_chm_file_check() {
  # $1 target fullpath
  [ -f "$1" ] || {
    echo "No such a file: $1" 1>&2
    exit 3
  }
}


_chm_main() {
  [ "$1" ] || {
    echo "No target file" 1>&2
    exit 2
  }

  _chm_system_check

  _chm_outputs.title "${_CHM_NAME} ${_CHM_VERSION}"

  for i in "$@"
  do
    local _chm_fullpath_list=("${_chm_fullpath_list[@]}" "$(readlink -f -- "${i}")")
  done

  for i in "${_chm_fullpath_list[@]}"
  do
    _chm_file_check "${i}"
  done

  for i in "${_chm_fullpath_list[@]}"
  do
    ${_CHM_LIBEXEC}/chocomint-main "${i}"

    [ -f "${_CHM_TEST_RESULTS_FILE}" ] && {
      source ${_CHM_TEST_RESULTS_FILE}
      rm ${_CHM_TEST_RESULTS_FILE}
    }
  done

  _chm_outputs.overall_results \
    "${_CHM_TEST_FAILURE}"     \
    "${_CHM_TEST_SUCCESS}"     \
    "${_CHM_TEST_COUNT}"       \
    "${_CHM_CMD_SUCCESS}"      \
    "${_CHM_CMD_COUNT}"

  ${_CHM_FAILURE} && return 1 || return 0
}

_chm_main "$@"
