#!/usr/bin/env bash
# vim: ft=sh

_chocomint_match_output() {
  # $1 right string
  # $2 stdout_file
  # $3 stderr_file
  if \egrep -q "$1" "$2" ||
     \egrep -q "$1" "$3"; then
    return 0
  else
    return 1
  fi
}

_chocomint_judge() {
  # $1 left string
  # $2 middle string
  # $3 right string
  # $4 exit status
  # $5 stdout_file
  # $6 stderr_file
  case $2 in
    "=" )
      if [ "$1" = "$3" ]; then
        return 0
      else
        return 1
      fi
      ;;
    "!=" )
      if [ "$1" != "$3" ]; then
        return 0
      else
        return 2
      fi
      ;;
    ":" )
      case $1 in
        'status' )
          [ $3 -ge 0 ] || chocomint_outputs.error "\`$3\`: Invalid status code"
          if [ $4 -eq $3 ]; then
            return 0
          else
            return 3
          fi
          ;;
        'output' )
          if _chocomint_match_output "$3" "$5" "$6"; then
            return 0
          else
            return 4
          fi
          ;;
        * )
          chocomint_outputs.error "\`$1\`: Invalid test label"
          ;;
      esac
      ;;
    "!:" )
      case $1 in
        'status' )
          [ $3 -ge 0 ] || chocomint_outputs.error "\`$3\`: Invalid status code"
          if [ $4 -ne $3 ]; then
            return 0
          else
            return 5
          fi
          ;;
        'output' )
          if _chocomint_match_output "$3" "$5" "$6"; then
            return 6
          else
            return 0
          fi
          ;;
        * )
          chocomint_outputs.error "\`$1\`: Invalid test label"
          ;;
      esac
      ;;
    * )
      chocomint_outputs.error "\`$2\`: Invalid operator"
      ;;
  esac
}

_chocomint_judge "$@"
