#!/usr/bin/env bash
# vim: ft=sh

_chocomint_match_file() {
  # $1 right string
  local _chocomint_matching=false
  local _chocomint_v="$1"
  shift

  for _chocomint_i in "$@"
  do
    if egrep -q "$_chocomint_v" "$_chocomint_i"; then
      _chocomint_matching=true
    fi
  done

  $_chocomint_matching && return 0 || return 1
}

_chocomint_judge() {
  # $1 left string
  # $2 middle string
  # $3 right string
  # $4 exit status
  case $2 in
    "=" )
      if [ "$1" = "$3" ]; then
        return 0
      else
        return 1
      fi
      ;;
    "!=" )
      if [ "$1" != "$3" ]; then
        return 0
      else
        return 1
      fi
      ;;
    ":" )
      case $1 in
        'status' )
          if [ $4 -eq $3 ]; then
            return 0
          else
            return 1
          fi
          ;;
        'output' )
          if _chocomint_match_file "$3" "$CHOCOMINT_CMD_OUT" "$CHOCOMINT_CMD_ERR"; then
            return 0
          else
            return 1
          fi
          ;;
        'stdout' )
          if _chocomint_match_file "$3" "$CHOCOMINT_CMD_OUT"; then
            return 0
          else
            return 1
          fi
          ;;
        'stderr' )
          if _chocomint_match_file "$3" "$CHOCOMINT_CMD_ERR"; then
            return 0
          else
            return 1
          fi
          ;;
      esac
      ;;
    "!:" )
      case $1 in
        'status' )
          if [ $4 -ne $3 ]; then
            return 0
          else
            return 1
          fi
          ;;
        'output' )
          if _chocomint_match_file "$3" "$CHOCOMINT_CMD_OUT" "$CHOCOMINT_CMD_ERR"; then
            return 1
          else
            return 0
          fi
          ;;
        'stdout' )
          if _chocomint_match_file "$3" "$CHOCOMINT_CMD_OUT"; then
            return 1
          else
            return 0
          fi
          ;;
        'stderr' )
          if _chocomint_match_file "$3" "$CHOCOMINT_CMD_ERR"; then
            return 1
          else
            return 0
          fi
          ;;
      esac
      ;;
  esac
}

_chocomint_judge "$@"
