#!/bin/bash
# vim: ft=sh

_chocomint_indent_echo() {
  local _chocomint_spaces=''

  for ((i=0; i<$1; i++)); do
    _chocomint_spaces="$_chocomint_spaces "
  done

  echo "$2" | sed "s/^/$_chocomint_spaces/" >&3
}


_chocomint_printf() {
  printf $@ >&3
}


_chocomint_echo() {
  echo "$@" >&3
}


_chocomint_eval_echo() {
  eval "_chocomint_echo $@"
}


_chocomint_tput() {
  tput $@ >&3
}


_chocomint_draw_ruler() {
  [ "$_CHOCOMINT_TERM_COLS" ] || {
    local _chocomint_cols=`tput _chocomint_cols 2>&4`
    for ((i=0; i<$_chocomint_cols; i++)); do
      _CHOCOMINT_TERM_COLS="$_CHOCOMINT_TERM_COLS""$1"
    done
  }
  _chocomint_echo "$_CHOCOMINT_TERM_COLS"
}
